# .github/workflows/deploy.yml

name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        # --- PERUBAHAN DI SINI ---
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            dist
            node_modules
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        # --- DAN PERUBAHAN DI SINI ---
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./deploy

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./deploy/*"
          target: "/home/yusuf/SMI-HIMPA-Server"
          strip_components: 1 # Menghapus folder 'deploy' saat menyalin

      - name: Install dependencies and restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/yusuf/SMI-HIMPA-Server
            # Menjalankan 'npm ci' akan menginstal dari package-lock.json
            npm ci --only=production
            pm2 restart smi-server